/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolucionesIndexRouteImport } from './routes/soluciones.index'
import { Route as SolucionesSlugRouteImport } from './routes/soluciones.$slug'

const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucionesIndexRoute = SolucionesIndexRouteImport.update({
  id: '/soluciones/',
  path: '/soluciones/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucionesSlugRoute = SolucionesSlugRouteImport.update({
  id: '/soluciones/$slug',
  path: '/soluciones/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/tienda': typeof TiendaRoute
  '/soluciones/$slug': typeof SolucionesSlugRoute
  '/soluciones/': typeof SolucionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/tienda': typeof TiendaRoute
  '/soluciones/$slug': typeof SolucionesSlugRoute
  '/soluciones': typeof SolucionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/tienda': typeof TiendaRoute
  '/soluciones/$slug': typeof SolucionesSlugRoute
  '/soluciones/': typeof SolucionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/tienda'
    | '/soluciones/$slug'
    | '/soluciones/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkout' | '/tienda' | '/soluciones/$slug' | '/soluciones'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/tienda'
    | '/soluciones/$slug'
    | '/soluciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  TiendaRoute: typeof TiendaRoute
  SolucionesSlugRoute: typeof SolucionesSlugRoute
  SolucionesIndexRoute: typeof SolucionesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soluciones/': {
      id: '/soluciones/'
      path: '/soluciones'
      fullPath: '/soluciones/'
      preLoaderRoute: typeof SolucionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soluciones/$slug': {
      id: '/soluciones/$slug'
      path: '/soluciones/$slug'
      fullPath: '/soluciones/$slug'
      preLoaderRoute: typeof SolucionesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  TiendaRoute: TiendaRoute,
  SolucionesSlugRoute: SolucionesSlugRoute,
  SolucionesIndexRoute: SolucionesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
